# General Jekyll Config
name: Scott Colfer
description: Blog about product management, product leadership, digital transformation, and coffee. Personal site for Scott Colfer.
url: "https://scottcolfer.com/"

# Build settings
markdown: kramdown
theme: minima
