# General Jekyll Config
title: Scott Colfer
name: Scott Colfer
description: Blog about product management, product leadership, digital transformation and coffee. This blog produces less CO2 than 99% of sites on the web. Check yours at WebsiteCarbon.com.
# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
google_analytics: G-NHPCNV8GX8

#Social links
github_username:  scottcolfer
linkedin_username: scottcolfer

#Commenting
disqus:
  shortname: scott-colfer

#Header pages
header_pages:
  - index.md
