# General Jekyll Config
Title: Scott Colfer
Author: 
  name: Scott Colfer
description: Blog about product management, product leadership, digital transformation and coffee. Personal site for Scott Colfer.
url: "https://scottcolfer.com/"
google_analytics: UA-20458896-5

# Build settings
markdown: kramdown
theme: minima

#Social links
twitter_username: scottcolfer
github_username:  scottcolfer
linkedin_username: scottcolfer

#Commenting
disqus:
  shortname: scott-colfer

#Header pages
header_pages:
  - about.md
  - index.md
